# Generated by Django 5.0.6 on 2024-07-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_cliente_eliminado_alter_direccion_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(choices=[('REGION_METROPOLITANA', 'Región Metropolitana de Santiago'), ('REGION_LOS_RIOS', 'Región de Los Ríos'), ('REGION_ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('REGION_MAGALLANES', 'Región de Magallanes y de la Antártica Chilena'), ('REGION_COQUIMBO', 'Región de Coquimbo'), ('REGION_VALPARAISO', 'Región de Valparaíso'), ('REGION_TARAPACA', 'Región de Tarapacá'), ('REGION_AISEN', 'Región Aisén del General Carlos Ibáñez del Campo'), ('REGION_ATACAMA', 'Región de Atacama'), ('REGION_NUBLE', 'Región de Ñuble'), ('REGION_ARAUCANIA', 'Región de La Araucanía'), ('REGION_LOS_LAGOS', 'Región de Los Lagos'), ('REGION_BIOBIO', 'Región del Biobío'), ('REGION_MAULE', 'Región del Maule'), ('REGION_ANTOFAGASTA', 'Región de Antofagasta'), ('REGION_BERNARDO_OHIGGINS', "Región del Libertador General Bernardo O'Higgins")], default='REGION_BIOBIO', max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('EN_PREPARACION', 'En preparacion')], default='EN_PREPARACION', max_length=100, null=True),
        ),
    ]
